config/routes.rb
Ssnotas::Application.routes.draw do

  resources :notas_attachment

  resources :estados_nota do
    get 'delete', on: :member
  end
  resources :nota_persona, only: :create
  resources :nota_persona do
     get 'delete', on: :collection
  end

  resources :home, only: :index
  root 'home#index'

  devise_for :users, path: "sessions", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock' }
  resources :users
  resources :users do
    member do
      get 'editpwd'
      post 'updatepwd'
    end
  end
  get "notas_recibidas/search"
  get "notas_recibidas"  => "notas_recibidas#index"
  get "notas_recibidas/:id" => "notas_recibidas#show" , as: "nota_recibida"
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :notas_temporales do
    get 'search', on: :collection
    get 'cupon', on: :member
    get 'barcode', on: :member

  end

  resources :notas_temporales

  resources :entidades do
    get 'change_es_facultad', on: :member
    get 'delete', on: :member
    get 'change_es_actual', on: :member
    get 'find_remitentes', on: :collection
    get 'find_destinatarios', on: :collection
    get 'get_actual_cargo_dependencia', on: :collection
    get 'search', on: :collection
  end
  resources :entidades

  resources :cargos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :personas do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "profile" => "profile#edit"
  post "profile/update" => "profile#update"
  get "profile/password" => "profile#password"
  post "profile/update_password" => "profile#update_password"

  resources :organismos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :notas do
    get 'search', on: :collection
    get 'search_pendientes', on: :collection
    get :new_dependencia,   :on => :collection
    post :create_dependencia,   :on => :collection
    get :new_remitente,   :on => :collection
    post :create_remitente,   :on => :collection
    get 'pendientes', on: :collection
    get 'edit_pendiente', on: :member
    post 'process_pendiente', on: :collection
    get 'barcode', on: :member
    post 'asociar', on: :collection
    get 'find_by', on: :collection
    get 'shortcut', on: :member
    get 'shortcut_pendiente', on: :member
    get 'att', on: :member    

  end

  resources :notas

  resources :destinatarios

  resources :autoridades

  resources :tipos_notas do
    get 'search', on: :collection
    get 'delete', on: :member
  end
  resources :remitentes do
    get :getByDependencia,   :on => :collection
  end

  resources :remitentes

  resources :dependencias do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "datatable_i18n" => "datatable"
end

app/models/dependencia.rb
class Dependencia < ActiveRecord::Base
  #registrar los cambios
  has_paper_trail
  default_scope order('nombre ASC')
  has_many :entidades, :dependent=>:restrict
  belongs_to :organismo

  attr_accessible :codigo, :descripcion, :nombre,  :organismo_id, :organismo, :alias
  validates :nombre, :presence =>{:message=>"Debe ingresar el nombre"}
  validates :codigo, :uniqueness => {:message => "No se puede repetir el Codigo" }
  #validates :organismo_id, :presence =>{:message=>"Debe seleccionar un organismo"}
  validates_uniqueness_of :nombre, scope: :organismo_id, :message => 'La dependencia ya existe en el Organismo seleccionado'

  #Antes de validar chequear si tiene codigo, sino crearlo
  before_validation :generateCode

  #Se fija si tiene codigo, sino lo crea
  def generateCode
    if self.codigo==nil  then
        temp=Dependencia.maximum(:codigo)
        self.codigo=temp==nil ? 1 : temp+1
    end

  end

=begin
  #No se si se esta usando 15-04-14
  def self.search(textsearch)
    if !textsearch.blank?  then
      joins("LEFT JOIN `organismos` ON dependencias.organismo_id = organismos.id").where('dependencias.nombre LIKE ? or organismos.nombre LIKE ? or dependencias.codigo = ?', "%#{textsearch}%", "%#{textsearch}%","#{textsearch}")
    else
      scoped.joins("LEFT JOIN `organismos` ON dependencias.organismo_id = organismos.id")
    end
  end
=end
  #REALIZA UNA BUSQUEDA SIMPLE DE UNA O MAS PALABRAS
  #complextext: puede contener palabras + y *
  def self.simpleSearch(complextext)
      if !complextext.blank?
          strwhere = "dependencias.nombre LIKE '%?%' or organismos.nombre LIKE '%?%' or dependencias.codigo = '?'"
          sqlwhere = Util::prepare_query(complextext,strwhere)
          joins("LEFT JOIN `organismos` ON dependencias.organismo_id = organismos.id").where(sqlwhere)
      else
          scoped.joins("LEFT JOIN `organismos` ON dependencias.organismo_id = organismos.id")
      end

  end



  def fullname
      name = ""
      if !self.organismo.nil?
          name += self.organismo.nombre+' -> '
      end
      name += self.nombre
  end
  def alias_or_name
      if self.alias.blank?
        self.nombre
      else
        self.alias
      end
  end
  def alias_or_fullname
      name = ""
      if !self.organismo.nil?
          name += self.organismo.alias_or_name+' -> '
      end
      name += self.alias_or_name
  end
end

app/controllers/dependencias_controller.rb
class DependenciasController < ApplicationController
#before_action :can_execute
  before_filter :authenticate_user!
  before_action :authenticate_manager
  # GET /dependencias
  # GET /dependencias.json
  def index
      find_dependencias
      respond_to do |format|
          format.html
          format.json { render :json => @dependencias.to_json(:methods => :alias_or_fullname, :only => [:id, :codigo, :nombre])}

      end
  end


  #Realiza la busqueda de dependencias
  #El texto a buscar viene en el parametro term
  #Retorna una vista parcial de row_index
  def search
      find_dependencias
      respond_to do |format|
          format.html{render :partial=> "row_index"}
          format.json { render json: @dependencias }
          format.js {  }
      end
  end


  # GET /dependencias/1
  # GET /dependencias/1.json
  def show
    @dependencia = Dependencia.find(params[:id])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dependencia }
    end
  end

  # GET /dependencias/new
  # GET /dependencias/new.json
  def new

    @dependencia = Dependencia.new
    @organismo = Organismo.all
    if (params[:remote]) then
        render "new", :layout => false

    else
      respond_to do |format|
        format.html
        format.json { render json: @dependencia }
      end
    end
  end

  # GET /dependencias/1/edit
  def edit
    @dependencia = Dependencia.find(params[:id])
    @organismo = Organismo.all
    if params[:remote]
        render :partial=> "form"
        return;
    end

  end

  # POST /dependencias
  # POST /dependencias.json
  def create
    @dependencia = Dependencia.new(dependencia_params)

    respond_to do |format|
      if @dependencia.save
        logger.info { params }
        format.html { redirect_to @dependencia, notice: 'Dependencia se creo correctamente.' }
        format.json { render json: @dependencia, status: :created, location: @dependencia }
        format.js {
           if params.has_key?("listado")
              @listado=true
           else
             @listado = false
           end
          }
      else
        @organismo = Organismo.all
        format.html { render action: "new" }
        format.json { render json: @dependencia.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PUT /dependencias/1
  # PUT /dependencias/1.json
  def update
    @dependencia = Dependencia.find(params[:id])

    respond_to do |format|
      if @dependencia.update_attributes(dependencia_params)
        format.html { redirect_to @dependencia, notice: 'Dependencia se actualizo correctamente.' }
        format.json { head :no_content }
        format.js{}
      else
        format.html { render action: "edit" }
        format.json { render json: @dependencia.errors, status: :unprocessable_entity }
        format.js{}
      end
    end
  end

  # DELETE /dependencias/1
  # DELETE /dependencias/1.json
  def destroy
    @dependencia = Dependencia.find(params[:id])
    begin
      @dependencia.destroy
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:error]="No se pudo eliminar porque otros dependen de el\n(#{e})"
    end
    respond_to do |format|
      format.html { redirect_to dependencias_url }
      format.json { head :no_content }
    end
  end
  def delete
    $ok = true
    @dependencia = Dependencia.find(params[:id])
    begin
        @dependencia.destroy
    rescue ActiveRecord::DeleteRestrictionError => e
          $ok = false
    end
    respond_to do |format|
        format.html{redirect_to cargos_url, notice: "Se elimino la dependencia #{dependencia.nombre}."}
        format.js{$ok}
    end
  end

private
  def dependencia_params
    params.require(:dependencia).permit(:codigo, :descripcion, :nombre,  :organismo_id, :organismo, :alias)
  end
  def can_execute
    if is_current_user_admin || is_current_user_sec_adm
      return true
    else
      flash[:error] = "No tiene permisos suficientes para ejecutar "+params[:action]
      redirect_to :log_in # halts request cycle
    end
  end
  def find_dependencias
      $valid_sort=['nombre','codigo','organismo']
      if params[:sort]!=nil && $valid_sort.include?(params[:sort]) then
          $dir=params[:direction]=='desc' ? "desc":"asc"
          if params[:sort]=='organismo' then
              $order="organismos.nombre " + $dir
          else
              $order=params[:sort]+" " + $dir
          end
      else
          $order="nombre ASC"
      end
      #$s=params[:search] || params[:term]
      $s=params[:term] || session[:term]
      if $s!=nil then
          $s=$s.gsub('%', '\%').gsub('_', '\_')
      end
      if params.key?(:fixed_organismo_id)
              @dependencias = Dependencia.where(organismo_id: params[:fixed_organismo_id]).simpleSearch($s).reorder($order).paginate(:page => params[:page], :per_page => params[:rows])
      else
          @dependencias = Dependencia.simpleSearch($s).reorder($order).paginate(:page => params[:page], :per_page => params[:rows])
      end
  end


end

app/helpers/dependencias_helper.rb
module DependenciasHelper
  #def readCodigos
  #  require 'yaml'
  #  result =  YAML::load_file("#{Rails.root}/app/helpers/dependencias_code.yml")
  #end
end

app/views/dependencias/_form.html.erb
  <% if @dependencia.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dependencia.errors.count, "error") %> produjo que la dependencia no se guardara:</h2>
      <ul>
        <% @dependencia.errors.each_with_index do |msg, i| %>
  		  <li><%= msg[1] %></li>
		<% end %>
	  </ul>
    </div>
  <% end %>
  <div id="message-remote"></div>
<%= form_for(@dependencia , :remote =>  params[:remote]) do |f| %>
 <% if params.has_key?("listado")%>
 <input type="hidden" name="listado" value="1" />
 <% end%>
  <div class="form-group">
    <%= f.label :nombre, :class=>"required" %><br />
    <%= f.text_field :nombre, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :alias %><br />
    <%= f.text_field :alias, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :descripcion %><br />
    <%= f.text_field :descripcion, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :organismo_id %><br />
    <%= f.select :organismo_id, @organismo.collect {|p| [ p.nombre, p.id ] },{:include_blank =>"Ninguna Organización"},{ :class=>"form-control"} %>
  </div>
  <div class="form-group">
    <%= f.label :codigo %><br />
    <%= f.number_field :codigo, :class=>"form-control" %>
  </div>
  <div class="form-group">
    <center><%= f.submit "Aceptar", :class => 'btn  btn-primary' %></center>
  </div>
<% end %>

app/views/dependencias/_row_index.html.erb
<%
if !@dependencias.empty?
    @dependencias.each do |dependencia|
        @dependencia=dependencia
        $cssclass=cycle('list-line-odd', 'list-line-even')
%>
<%= render partial: 'single_row_index' %>
  <% end %>
<div class="row">
<div class="tfoot">
<%= ajax_will_paginate @dependencias, :id=>"div_pag_ajax", :previous_label=>"&lt;&lt;Ant", :next_label=>"Sig&gt;&gt;", :remote=>"true" %>
</div>
</div>
<%
  else
%>
<div class="row">
  <div  class="col-xs-12 col-sm-12 col-md-12  col-lg-12">
  <h2>No se encontraron resultados</h2>
  </div>
</div>

<% end %>

app/views/dependencias/_single_row_index.html.erb
<%
if @cssclass.nil?
  @cssclass= 'list-line-odd'
end
%>
  <div id="dependencia_<%= @dependencia.id %>" class="row <%= $cssclass unless $cssclass.nil? %>">
    <div class="datagrid-cell">
      <div id="dependencia_<%= @dependencia.id %>_id" class="col-xs-1 col-sm-1 col-md-1  col-lg-1"><%= @dependencia.id %></div>
      <div id="dependencia_<%= @dependencia.id %>_nombre" class="col-xs-3 col-sm-3 col-md-3  col-lg-3"><%= @dependencia.nombre %></div>
      <div id="dependencia_<%= @dependencia.id %>_descripcion" class="col-xs-2 col-sm-2 col-md-2  col-lg-2"><%= @dependencia.descripcion %></div>
      <div id="dependencia_<%= @dependencia.id %>_codigo" class="col-xs-1 col-sm-1 col-md-1  col-lg-1"><%= @dependencia.codigo %></div>
      <div id="dependencia_<%= @dependencia.id %>_organismo" class="col-xs-3 col-sm-3 col-md-3  col-lg-3"><%= @dependencia.organismo.nombre unless @dependencia.organismo.nil? %></div>
      <div class="col-xs-2 col-sm-2 col-md-2  col-lg-2"  style="text-align: right;">

         <div class="btn-group" style="margin-top: 3px; margin-bottom: 3px;">

           <%= link_to image_tag("view16x16.png",{:align => "middle",  :alt=>"Ver", :border => "0"}), @dependencia ,{:title =>"Ver más información", :class=>"boton-row"}%>

           <% if ! mobile_device? %>
              <%= link_to image_tag("edit16x16.png",{:align => "middle", :alt=>"Editar", :border => "0"}), "#",{:title =>"Editar", :class=>"boton-row", :onClick=>"return editDependencia('#{edit_dependencia_path(@dependencia,:remote=>true)}');"}%>
              <%= link_to image_tag("delete16x16.png",{:align => "middle",  :alt=>"Eliminar", :border => "0"}), delete_dependencia_path(@dependencia), {data: { confirm: 'Eliminara la dependencia. ¿Esta seguro?' },:title =>"Eliminar", :class=>"boton-row",:remote=>true }%>
           <% else %>

                 <%= link_to image_tag("edit16x16.png",{:align => "middle", :alt=>"Editar", :border => "0"}), edit_dependencia_path(@dependencia),{:title =>"Editar", :class=>"boton-row"}%>
                 <%= link_to image_tag("delete16x16.png",{:align => "middle",  :alt=>"Eliminar", :border => "0"}), @dependencia, {method: :delete, data: { confirm: 'Eliminara el dependencia. ¿Esta seguro?' },:title =>"Eliminar", :class=>"boton-row"}%>
           <% end %>

           <%=
           #
           %>
         </div>
      </div>
    </div>
  </div>

app/views/dependencias/create.js.erb
/*EL PARAMETRO $listado lo defino cuando la accion que lo llama es crear desde el listado de dependencias
 porque en este caso tiene que actualiar el listado, este metodo tambien se invoca desde crear entidad
 ahi podes llamar a crear dependencia, y en este caso solo tiene que definir un metodo javascript
 llamado postCreateDependencia y se le pasa el json del objeto creado*/
<%
  if @listado
%>
      <% if @dependencia.valid? %>

        $("#message-remote").html('<p class="alert">La Dependencia se guardo correctamente</p>');
        $("#listado-cargos").append("<%= escape_javascript(render("single_row_index"))%>");
      <%
         else
             strerror="<h3>"+pluralize(@dependencia.errors.count, "Error")+ " produjo que la Dependencia no se guardara:</h3>"

             @cargo.errors.each_with_index do |msg, i|
                strerror +='<p class="error">'+ msg[1] +'</p>'
             end

      %>

             $("#message-remote").html('<%= raw(strerror) %>');

      <% end %>
<% else %>
    <%- if @dependencia.errors.any? %>
        var errores="";
        <% @dependencia.errors.each_with_index do |msg, i| %>
              errores += "<%= msg[1] %>\n";
        <% end %>
        alert(errores);

    <%- else %>
      postCreateDependencia('<%= @dependencia.to_json(:methods => [:fullname, :alias_or_fullname]).html_safe %>');
    <%- end %>
<% end %>

app/views/dependencias/delete.js.erb
<% #Llamado cuando se crea un dependencia con ajax
#Simplemente informar el resultado del metodo create
%>


<% if $ok %>
   $("#dependencia_<%= @dependencia.id %>").fadeOut("slow",new function(){$("#dependencia_<%= @dependencia.id %>").remove();});

<%
   else
%>
$('body').append("<div id='tempmsj'></div>");
$('#tempmsj').dialog({
                        autoOpen: false,
                        resizable: false,
                        show: 'fade',
                        hide: 'fade',
                        height: 140,
                        modal: true,
                        title: 'No se pudo eliminar',
                        close: function (event, ui) { $('#tempmsj').remove();},
                        open: function (event, ui) {
                          $('#tempmsj').html('<p>Existen registros que dependenden de esta dependencia</p>');
                        }
                    }).dialog("open");

setTimeout(function () { $('#tempmsj').dialog("close"); }, 2000);

<% end %>

app/views/dependencias/edit.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(@dependencia,"Mostrar", "view16x16.png", {:title =>"Mostrar Dependencia", :alt=>"Mostrar"})%>
  <%= navBarLink(dependencias_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Dependencias", :alt=>"Listar"})%>
</nav>

<div class="formulario">
    <div class="row">
      <div class="col-xs-6  col-sm-6  col-md-6  col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">
    <h1>Editar Dependencia</h1>
 <%= render 'form' %>
      </div>
    </div>
</div>

app/views/dependencias/index.html.erb
<script>
<%= helper_script_dialog_create('openDependencia','modal-dependencia',new_dependencia_path(:remote=>true,:listado=>true),"Nueva Dependencia",600,450) %>
<%= helper_script_dialog_edit('editDependencia','modal-dependencia',"Editar Dependencia",600,450) %>
</script>

<%
cabecera = [{:size=>1, :name=>"ID"},
            {:size=>3, :name=>"Nombre",:sort=>'nombre'},
            {:size=>2, :name=>"Descripción"},
            {:size=>1, :name=>"Codigo",:sort=>'codigo'},
            {:size=>3, :name=>"Organismo",:sort=>'organismo'},
           ]
%>
<% if ! mobile_device? %>
  <%= helper_datagrid_header("Listado de Dependencias",{:controller=>'dependencias', :action=>'search'},{:label=>'Nueva Dependencia',:action=>"return openDependencia();", :remote=>true},cabecera,'listado-dependencias') %>
<% else %>
  <%= helper_datagrid_header("Listado de Dependencias",{:controller=>'dependencias', :action=>'search'},{:label=>'Nueva Dependencia',:action=>new_dependencia_path },cabecera,'listado-dependencias') %>
  <% end %>
<div id="listado-dependencias" class="paginaremota">
<%= render partial: 'row_index' %>
</div>

app/views/dependencias/new.html.erb
<% if params[:remote] %>
    <div class="formulario">
      <div class="row">
        <div class="col-xs-12  col-sm-12  col-md-8  col-lg-8 col-md-offset-2  col-lg-offset-2">
          <%= render 'form' %>
        </div>
      </div>
    </div>
<% else %>

  <nav class="navbar" role="navigation">
    <%= navBarLink(dependencias_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Dependencias", :alt=>"Listar"})%>
  </nav>
  <div class="formulario">
    <div class="row">
      <div class="col-xs-12  col-sm-12  col-md-8  col-lg-8 col-md-offset-2  col-lg-offset-2">
        <h1>Nueva Dependencia</h1>
        <%= render 'form' %>
     </div>
    </div>
   </div>

<% end %>

app/views/dependencias/search.js.erb
<!-- Llamado por search cuando se realiza una busqueda con ajax, -->
$('.paginaremota').html("<%= escape_javascript(render("row_index"))%>");

<!--#LLamado cuando se realiza la paginacion por ajax -->

app/views/dependencias/show.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(edit_dependencia_path(@dependencia),"Editar", "edit16x16.png", {:title =>"Editar Dependencia", :alt=>"Editar"})%>
  <%= navBarLink(dependencias_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Dependencias", :alt=>"Listar"})%>
</nav>


<div class="box-key-values">
    <h1>Detalle sobre la Dependencia</h1>
<p>
  <span class="text-key">Nombre:</span>
  <%= @dependencia.nombre %>
</p>
<p>
  <span class="text-key">Alias:</span>
  <%= @dependencia.alias %>
</p>

<p>
  <span class="text-key">Descripcion:</span>
  <%= @dependencia.descripcion %>
</p>

<p>
  <span class="text-key">Codigo:</span>
  <%= @dependencia.codigo %>
</p>

<p>
  <span class="text-key">Organismo:</span>
  <%= @dependencia.organismo.try :nombre %>
</p>

</div>

app/views/dependencias/update.js.erb
<% #Llamado cuando se crea un dependencia con ajax
#Simplemente informar el resultado del metodo create
%>

<% if @dependencia.valid? %>

 $('#dependencia_<%= @dependencia.id %>').replaceWith("<%= escape_javascript(render("single_row_index"))%>");
$("#modal-dependencia").dialog( "close" );
<%
   else
       strerror="<h3>"+pluralize(@dependencia.errors.count, "Error")+ " produjo que la dependencia no se guardara:</h3>"
       @dependencia.errors.each_with_index do |msg, i|
          strerror +='<p class="error">'+ msg[1] +'</p>'
       end
%>
$("#message-remote").html('<%= raw(strerror) %>');
<% end %>