config/routes.rb
Ssnotas::Application.routes.draw do

  resources :notas_attachment

  resources :estados_nota do
    get 'delete', on: :member
  end
  resources :nota_persona, only: :create
  resources :nota_persona do
     get 'delete', on: :collection
  end

  resources :home, only: :index
  root 'home#index'

  devise_for :users, path: "sessions", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock' }
  resources :users
  resources :users do
    member do
      get 'editpwd'
      post 'updatepwd'
    end
  end
  get "notas_recibidas/search"
  get "notas_recibidas"  => "notas_recibidas#index"
  get "notas_recibidas/:id" => "notas_recibidas#show" , as: "nota_recibida"
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :notas_temporales do
    get 'search', on: :collection
    get 'cupon', on: :member
    get 'barcode', on: :member

  end

  resources :notas_temporales

  resources :entidades do
    get 'change_es_facultad', on: :member
    get 'delete', on: :member
    get 'change_es_actual', on: :member
    get 'find_remitentes', on: :collection
    get 'find_destinatarios', on: :collection
    get 'get_actual_cargo_dependencia', on: :collection
    get 'search', on: :collection
  end
  resources :entidades

  resources :cargos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :personas do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "profile" => "profile#edit"
  post "profile/update" => "profile#update"
  get "profile/password" => "profile#password"
  post "profile/update_password" => "profile#update_password"

  resources :organismos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :notas do
    get 'search', on: :collection
    get 'search_pendientes', on: :collection
    get :new_dependencia,   :on => :collection
    post :create_dependencia,   :on => :collection
    get :new_remitente,   :on => :collection
    post :create_remitente,   :on => :collection
    get 'pendientes', on: :collection
    get 'edit_pendiente', on: :member
    post 'process_pendiente', on: :collection
    get 'barcode', on: :member
    post 'asociar', on: :collection
    get 'find_by', on: :collection
    get 'shortcut', on: :member
    get 'shortcut_pendiente', on: :member
    get 'att', on: :member    

  end

  resources :notas

  resources :destinatarios

  resources :autoridades

  resources :tipos_notas do
    get 'search', on: :collection
    get 'delete', on: :member
  end
  resources :remitentes do
    get :getByDependencia,   :on => :collection
  end

  resources :remitentes

  resources :dependencias do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "datatable_i18n" => "datatable"
end

app/models/cargo.rb
class Cargo < ActiveRecord::Base
  has_paper_trail
  has_many :entidades, :dependent=>:restrict
  attr_accessible :nombre, :descripcion
  validates :nombre, :presence =>{:message=>"Debe ingresar el nombre del cargo"} , :uniqueness => { :message => "No se puede repetir el Cargo" }


=begin
  #No se si se esta usando 15-04-14

  def self.search(search)
    if search  then
      where('nombre LIKE ?', "%#{search}%")
    else
      scoped
    end
  end
=end
   #REALIZA UNA BUSQUEDA SIMPLE DE UNA O MAS PALABRAS
  #complextext: puede contener palabras + y *
  def self.simpleSearch(complextext)
      if !complextext.blank?
          strwhere = "nombre LIKE '%?%'"
          sqlwhere = Util::prepare_query(complextext,strwhere)
          where(sqlwhere)
      else
          scoped
      end
  end

end

app/controllers/cargos_controller.rb
class CargosController < ApplicationController
  before_action :set_cargo, only: [:show, :edit, :update, :destroy, :delete]
  before_filter :authenticate_user!
  before_action :authenticate_manager
  #before_action :can_execute

  # GET /cargos
  def index
    find_cargos
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cargos.to_json(:only => [:id, :nombre])}
    end

  end

  #Realiza la busqueda de cargos
  #El texto a buscar viene en el parametro term
  #Retorna una vista parcial de row_index
  def search
      find_cargos
      logger.info params
      respond_to do |format|
          format.html{render :partial=> "row_index"}
          format.json { render json: @cargos }
          format.js {  }
      end

  end

  # GET /cargos/1
  def show
    @cargo = Cargo.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cargo }
    end
  end

  # GET /cargos/new
  def new
    @cargo = Cargo.new
    if params[:remote]
        render :partial=> "form"
        return;
    end

  end

  # GET /cargos/1/edit
  def edit
    @cargo = Cargo.find(params[:id])
    if params[:remote]
        render :partial=> "form"
        return;
    end
  end

  # POST /cargos
  def create
    @cargo = Cargo.new(cargo_params)
    respond_to do |format|
      if @cargo.save
        format.html{
          logger.info("HTML")
          redirect_to @cargo, notice: 'El Cargo se creo correctamente.'}
        format.json {
          logger.info("JSON")
          render json: @cargo, status: :created, location: @cargo }
        format.js{}
      else
        format.html { render action: "new" }
        format.json { render json: @cargo.errors, status: :unprocessable_entity }
        format.js{}
      end
    end

  end

  # PATCH/PUT /cargos/1
  def update
    if @cargo.update(cargo_params)
      respond_to do |format|
          format.html{redirect_to @cargo, notice: 'El cargo se modifico correctamente.'}
          format.js{}
      end
    else
       respond_to do |format|
          format.html{render action: 'edit'}
          format.js{}
        end
    end
  end

  # DELETE /cargos/1
  def destroy
    @cargo.destroy
    redirect_to cargos_url, notice: 'El cargo se elimino.'
  end
  def delete
    $ok = true
    begin
        @cargo.destroy
    rescue ActiveRecord::DeleteRestrictionError => e
          $ok = false
    end
    respond_to do |format|
        format.html{redirect_to cargos_url, notice: 'El cargo se elimino.'}
        format.js{$ok}
    end
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cargo
      @cargo = Cargo.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cargo_params
      params.require(:cargo).permit(:nombre, :descripcion)
    end
=begin
    def can_execute
      if is_current_user_admin || is_current_user_sec_adm
        return true
      else
        flash[:error] = "No tiene permisos suficientes para ejecutar "+params[:action]
        redirect_to :log_in # halts request cycle
      end
    end
=end

    def find_cargos
        if params[:sort]!=nil && params[:sort]=="nombre" then
          dir=params[:direction]=='desc' ? "desc":"asc"
          order="nombre " + dir
        else
          order="nombre ASC"
        end

        s=params[:term] || session[:term]
        ###TENGO QUE ASEGURAR QUE PAGE Y ROW EXISTAN Y SEAN NUMERICOS
          p=  params[:page].to_i != 0 ? params[:page].to_i : 1
          r=  params[:rows].to_i != 0 ? params[:rows].to_i : 99999
        # si no hay texto de busqueda, entonces debe listar todos con page=>nil
        if !s.blank? then
          s=s.gsub('%', '\%').gsub('_', '\_')

          @cargos = Cargo.simpleSearch(s).order(order).paginate(:page => p, :per_page => r)
        else
            @cargos = Cargo.all().order(order).paginate(:page => p, :per_page => r)#:page => params[:page], :per_page => params[:rows])
        end

    end
end

app/helpers/cargos_helper.rb
module CargosHelper
end

app/views/cargos/_form.html.erb
  <% if @cargo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cargo.errors.count, "error") %> produjo que el cargo no se guardara:</h2>

      <ul>
      <% @cargo.errors.each_with_index do |msg, i| %>
          <li><%= msg[1] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div id="message-remote"></div>
<%= form_for @cargo,:html=>{ :class=>"form", :role=>"form",  :remote =>  params[:remote] } do |f| %>
  <div class="form-group">
    <%= f.label :nombre, :class => 'required' %><br>
    <%= f.text_field :nombre, :class => 'form-control' %>
  </div>
    <div class="form-group">
    <%= f.label :descripcion %><br>
    <%= f.text_field :descripcion, :class => 'form-control' %>
  </div>
  <div class="form-group">
    <center><%= f.submit "Aceptar", :class => 'btn  btn-primary' %></center>
  </div>
<% end %>

app/views/cargos/_row_index.html.erb
<%
if !@cargos.empty?
    @cargos.each do |cargo|
        @cargo=cargo
        @cssclass=cycle('list-line-odd', 'list-line-even')
%>
<%= render partial: 'single_row_index' %>
  <% end %>
<div class="row">
<div class="tfoot">
<%= ajax_will_paginate $cargos, :id=>"div_pag_ajax", :previous_label=>"&lt;&lt;Ant", :next_label=>"Sig&gt;&gt;", :remote=>"true" %>
</div>
</div>
<%
  else
%>
<div class="row">
  <div  class="col-xs-12 col-sm-12 col-md-12  col-lg-12">
  <h2>No se encontraron resultados</h2>
  </div>
</div>

<% end %>

<script>
/*<!-- Esto tiene que ir en todos los archivos row
   Es para que setee la configuracion corriente ya que se carga por
   ajax
  $('#page').val('<%= params[:page] %>');
  $('#rows').val('<%= params[:rows] %>');
  $('#sort').val('<%= params[:sort] %>');
  $('#direction').val('<%= params[:direction] %>');
-->*/
</script>

app/views/cargos/_single_row_index.html.erb
<%
if @cssclass.nil?
  @cssclass= 'list-line-odd'
end
%>
  <div id="cargo_<%= @cargo.id %>" class="row <%= @cssclass unless @cssclass.nil? %>">
    <div class="datagrid-cell">
      <div  class="col-xs-1 col-sm-1 col-md-1  col-lg-1"><%= @cargo.id %></div>
      <div class="col-xs-5 col-sm-5 col-md-5  col-lg-5"><%= @cargo.nombre %></div>
      <div class="col-xs-4 col-sm-4 col-md-4  col-lg-4"><%= @cargo.descripcion %></div>
      <div class="col-xs-2 col-sm-2 col-md-2  col-lg-2"  style="text-align: right;">

         <div class="btn-group col-button">

           <%= link_to image_tag("view16x16.png",{:align => "middle",  :alt=>"Ver", :border => "0"}), @cargo ,{:title =>"Ver más información", :class=>"boton-row"}%>

           <% if ! mobile_device? %>
              <%= link_to image_tag("edit16x16.png",{:align => "middle", :alt=>"Editar", :border => "0"}), "#",{:title =>"Editar", :class=>"boton-row", :onClick=>"return openEditCargo('#{edit_cargo_path(@cargo,:remote=>true)}');"}%>
              <%= link_to image_tag("delete16x16.png",{:align => "middle",  :alt=>"Eliminar", :border => "0"}), delete_cargo_path(@cargo), {data: { confirm: 'Eliminara el Cargo. ¿Esta seguro?' },:title =>"Eliminar", :class=>"boton-row",:remote=>true }%>
           <% else %>

                 <%= link_to image_tag("edit16x16.png",{:align => "middle", :alt=>"Editar", :border => "0"}), edit_cargo_path(@cargo),{:title =>"Editar", :class=>"boton-row"}%>
                 <%= link_to image_tag("delete16x16.png",{:align => "middle",  :alt=>"Eliminar", :border => "0"}), @cargo, {method: :delete, data: { confirm: 'Eliminara el Cargo. ¿Esta seguro?' },:title =>"Eliminar", :class=>"boton-row"}%>
           <% end %>

           <%=
           #
           %>
         </div>
      </div>
    </div>
  </div>

app/views/cargos/create.js.erb
<% #Llamado cuando se crea un cargo con ajax
#Simplemente informar el resultado del metodo create
%>
<% if @cargo.valid? %>

  $("#message-remote").html('<p class="alert">El cargo se guardo correctamente</p>');
  $("#listado-cargos").append("<%= escape_javascript(render("single_row_index"))%>");
<%
   else
       strerror="<h3>"+pluralize(@cargo.errors.count, "Error")+ " produjo que el cargo no se guardara:</h3>"

       @cargo.errors.each_with_index do |msg, i|
          strerror +='<p class="error">'+ msg[1] +'</p>'
       end

%>

$("#message-remote").html('<%= raw(strerror) %>');

<% end %>

app/views/cargos/delete.js.erb
<% #Llamado cuando se crea un cargo con ajax
#Simplemente informar el resultado del metodo create
%>


<% if $ok %>
   $("#cargo_<%= @cargo.id %>").fadeOut("slow",new function(){$("#cargo_<%= @cargo.id %>").remove();});

<%
   else
%>
$('body').append("<div id='tempmsj'></div>");
$('#tempmsj').dialog({
                        autoOpen: false,
                        resizable: false,
                        show: 'fade',
                        hide: 'fade',
                        height: 140,
                        modal: true,
                        title: 'No se pudo eliminar',
                        close: function (event, ui) { $('#tempmsj').remove();},
                        open: function (event, ui) {
                          $('#tempmsj').html('<p>Existen personas con este cargo</p>');
                        }
                    }).dialog("open");

setTimeout(function () { $('#tempmsj').dialog("close"); }, 2000);

<% end %>

app/views/cargos/edit.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(@cargo,"Mostrar", "view16x16.png", {:title =>"Mostrar Cargo", :alt=>"Mostrar"})%>
  <%= navBarLink(cargos_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Cargos", :alt=>"Listar"})%>
</nav>

<div class="formulario">
    <div class="row">
      <div class="col-xs-6  col-sm-6  col-md-6  col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">
    <h1>Editar cargo</h1>
 <%= render 'form' %>
      </div>
    </div>
</div>

app/views/cargos/index.html.erb
<%
cabecera = [{:size=>1, :name=>"ID"},
            {:size=>5, :name=>"Nombre",:sort=>'nombre'},
            {:size=>4, :name=>"Descripción"}
           ]
%>
<% if ! mobile_device? %>
  <%= helper_datagrid_header("Listado de Cargos",{:controller=>'cargos', :action=>'search'},{:label=>'Nuevo Cargo',:action=>"return openNuevoCargo();", :remote=>true},cabecera,'listado-cargos') %>
<% else %>
  <%=helper_datagrid_header("Listado de Cargos",{:controller=>'cargos', :action=>'search'},{:label=>'Nuevo Cargo',:action=>new_cargo_path},cabecera,'listado-cargos')%>
<% end %>
<div id="listado-cargos" class="paginaremota">
<%= render partial: 'row_index' %>
</div>
<script>
/*
 * Abre una ventana para crear nuevos Cargos
 * */
function openNuevoCargo(){
    $('body').append("<div id='modal-cargo'></div>");
    url = "<%= url_for :controller =>"cargos", :action=>'new', :remote=>'true'  %>";
    $.ajax({
       type: "GET"
       , url: url
       , dataType:"html"
       , success: function(data){
            $("#modal-cargo").html(data);
       }
    });
    /*Especifica al div creado recientemente como dialog*/
    $("#modal-cargo").dialog({
        autoOpen: false,
        height: 350,
        width: 600,
        modal: true,
        title: 'Crear un nuevo Cargo',
        close: function(event, ui) { $('#modal-cargo').remove();},
    });
    $("#modal-cargo").dialog( "open" );
}


function openEditCargo(url){
    //Crea un div donde pondra el formulario
    $('body').append("<div id='modal-cargo'></div>");
    $.ajax({
       type: "GET"
       , url: url
       , dataType:"html"
       , success: function(data){
            $("#modal-cargo").html(data);
       }
    });
    /*Especifica al div creado recientemente como dialog*/
    $("#modal-cargo").dialog({
        autoOpen: false,
        height: 350,
        width: 600,
        modal: true,
        title: 'EditarCargo',
        close: function(event, ui) { $('#modal-cargo').remove();},

    });
    $("#modal-cargo").dialog( "open" );
}
</script>

app/views/cargos/new.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(cargos_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Cargos", :alt=>"Listar"})%>
</nav>

<div class="formulario">
    <div class="row">
      <div class="col-xs-6  col-sm-6  col-md-6  col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">
        <h1>Nuevo cargo</h1>
        <%= render 'form' %>
      </div>
    </div>
</div>

app/views/cargos/search.js.erb
<!-- Llamado por search cuando se realiza una busqueda con ajax, -->
$('.paginaremota').html("<%= escape_javascript(render("row_index"))%>");

<!--#LLamado cuando se realiza la paginacion por ajax -->

app/views/cargos/show.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(edit_cargo_path(@cargo),"Editar", "edit16x16.png", {:title =>"Editar Cargo", :alt=>"Editar"})%>
  <%= navBarLink(cargos_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Cargos", :alt=>"Listar"})%>
</nav>

     <div class="box-key-values">
        <h1>Detalle sobre el Cargo</h1>
        <p>
          <span class="text-key">Nombre:</span>
          <%= @cargo.nombre %>
        </p>
        <p>
          <span class="text-key">Descripcion:</span>
          <%= @cargo.descripcion %>
        </p>
        <% if !@cargo.entidades.empty? %>
        <hr>
        <h2>Personas que tiene este cargo</h2>
        <%
 @cargo.entidades.each do |entidad|
%>
<p><span class="text-key"><%= entidad.persona.fullname%></span> <%= entidad.dependencia.alias_or_fullname%></p>
<%
 end
%>

        <% end%>
     </div>

app/views/cargos/update.js.erb
<% #Llamado cuando se crea un cargo con ajax
#Simplemente informar el resultado del metodo create
%>
<% if @cargo.valid? %>
 $('#cargo_<%= @cargo.id %>').replaceWith("<%= escape_javascript(render("single_row_index"))%>");
$("#modal-cargo").dialog( "close" );
<%
   else
       strerror="<h3>"+pluralize(@cargo.errors.count, "Error")+ " produjo que el cargo no se guardara:</h3>"
       @cargo.errors.each_with_index do |msg, i|
          strerror +='<p class="error">'+ msg[1] +'</p>'
       end
%>
$("#message-remote").html('<%= raw(strerror) %>');
<% end %>