config/routes.rb
Ssnotas::Application.routes.draw do

  resources :notas_attachment

  resources :estados_nota do
    get 'delete', on: :member
  end
  resources :nota_persona, only: :create
  resources :nota_persona do
     get 'delete', on: :collection
  end

  resources :home, only: :index
  root 'home#index'

  devise_for :users, path: "sessions", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock' }
  resources :users
  resources :users do
    member do
      get 'editpwd'
      post 'updatepwd'
    end
  end
  get "notas_recibidas/search"
  get "notas_recibidas"  => "notas_recibidas#index"
  get "notas_recibidas/:id" => "notas_recibidas#show" , as: "nota_recibida"
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :notas_temporales do
    get 'search', on: :collection
    get 'cupon', on: :member
    get 'barcode', on: :member

  end

  resources :notas_temporales

  resources :entidades do
    get 'change_es_facultad', on: :member
    get 'delete', on: :member
    get 'change_es_actual', on: :member
    get 'find_remitentes', on: :collection
    get 'find_destinatarios', on: :collection
    get 'get_actual_cargo_dependencia', on: :collection
    get 'search', on: :collection
  end
  resources :entidades

  resources :cargos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :personas do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "profile" => "profile#edit"
  post "profile/update" => "profile#update"
  get "profile/password" => "profile#password"
  post "profile/update_password" => "profile#update_password"

  resources :organismos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :notas do
    get 'search', on: :collection
    get 'search_pendientes', on: :collection
    get :new_dependencia,   :on => :collection
    post :create_dependencia,   :on => :collection
    get :new_remitente,   :on => :collection
    post :create_remitente,   :on => :collection
    get 'pendientes', on: :collection
    get 'edit_pendiente', on: :member
    post 'process_pendiente', on: :collection
    get 'barcode', on: :member
    post 'asociar', on: :collection
    get 'find_by', on: :collection
    get 'shortcut', on: :member
    get 'shortcut_pendiente', on: :member
    get 'att', on: :member    

  end

  resources :notas

  resources :destinatarios

  resources :autoridades

  resources :tipos_notas do
    get 'search', on: :collection
    get 'delete', on: :member
  end
  resources :remitentes do
    get :getByDependencia,   :on => :collection
  end

  resources :remitentes

  resources :dependencias do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "datatable_i18n" => "datatable"
end

app/controllers/entidades_controller.rb
class EntidadesController < ApplicationController
  include EntidadesHelper
  respond_to :html, :json, :js
  helper_method :parse_text_to_cargo_persona
  before_action :set_entidad, only: [:show, :edit, :update, :destroy, :change_es_facultad, :change_es_actual, :delete]
  #before_action :can_execute
  before_filter :authenticate_user!
  before_action :authenticate_manager
  # GET /entidades
  def index
    if (params[:persona_id])
      return self.entidades_persona
    else
      find_entidades
    end
  end

  #Realiza la busqueda de entidades
  #El texto a buscar viene en el parametro term
  #Retorna una vista parcial de row_index
  def search
      find_entidades
      respond_to do |format|
          format.html{render :partial=> "row_index"}
          format.json { render json: @entidades }
          format.js {}
      end
  end

  # GET /entidades/1
  def show
  end


  # GET /entidades/new
  def new
    #Invoca al formulario para dar de alta una entidad.
    #Los posibles parametros son
    # fixed_persona_id: indica el id de la persona, no se puede seleccionar otra
    # fixed_dependencia_id: indica el id de la dependencia, no se puede seleccionar otra
    # fixed_organismo_id: indica el id del organismo, solo se listaran las dependencias de este organismo
    # fixed_cargo_id: indica el id del cargo, no se puede seleccionar otro
    # remote: si es un llamado remoto, no hay que devolver con layout
    # cargo_persona: indica que se procesa una nota temporal

    @entidad = Entidad.new
    if params.key?(:fixed_persona_id)
        @entidad.persona=Persona.find(params[:fixed_persona_id])
        @entidad.persona_id=params[:fixed_persona_id]
    elsif params.key?(:persona_id)
      @entidad.persona=Persona.find(params[:persona_id])
    end
    if params.key?(:fixed_cargo_id)
        @entidad.cargo=Cargo.find(params[:fixed_cargo_id])
        @entidad.cargo_id=params[:fixed_cargo_id]
    elsif params.key?(:cargo_id)
        @entidad.cargo=Cargo.find(params[:cargo_id])
    end

    #@personas = Persona.all
    #@cargos = Cargo.all
    #@usuarios = User.missing
    if params.key?(:fixed_dependencia_id)
        ##Este es el caso donde se debe agregar una entidad a una dependencia, y no permitir seleccionar la dependencia
         @entidad.dependencia = Dependencia.find(params[:fixed_dependencia_id])
         @entidad.dependencia_id = params[:fixed_dependencia_id]
    else
         if params.key?(:fixed_organismo_id)
              @dependencias = Dependencia.where(organismo_id: params[:fixed_organismo_id])
         else
              @dependencias = Dependencia.all
         end
         if params.key?(:dependencia_id)
               @entidad.dependencia = Dependencia.find(params[:dependencia_id])
               @entidad.dependencia_id = params[:dependencia_id]
         end
    end

    # SI VIENE EL PARAMETRO cargo_persona, significa que se esta procesando
    # una nota temporal, con lo cual habria que buscar
    # si existiese el cargo y/o la persona  setearselo a @entidad
    # si no existiese en la vista deberia quedar escrito para que lo agregue
    # el formato de cargo_persona deberia ser "cargo: apellido, nombre"
    if (params[:cargo_persona])
        @cargopersona= parse_text_to_cargo_persona(params[:cargo_persona])
        params[:persona_fullname]=@cargopersona[:persona_text]
        params[:cargo_fullname]=@cargopersona[:cargo_text]
        @entidad.persona=@cargopersona[:persona]
        @entidad.persona_id=@entidad.persona.id unless @entidad.persona.nil?
        @entidad.cargo = @cargopersona[:cargo]
        @entidad.cargo_id = @entidad.cargo.id unless @entidad.cargo.nil?
    end
    if (params[:remote]) then
      if (params[:bt])
        render "/entidades/bt/new", :layout => false
      else
        # render "new", :layout => false
        render "/entidades/bt/new", :layout => false

      end
    else
        respond_to do |format|
          format.html
        end
    end
  end

  # GET /entidades/1/edit
  def edit
    @entidad = Entidad.find(params[:id])
    @dependencias = Dependencia.all
    @personas = Persona.all
    @cargos = Cargo.all
    @usuarios = User.missing
    if (params[:remote]) then
        render "/entidades/bt/edit", :layout => false
        # render "edit", :layout => false
    else
        respond_to do |format|
          format.html
        end
    end
  end

  # POST /entidades
  def create
    @entidad = Entidad.new(entidad_params)

    ok=true
    if params[:entidad][:es_actual] && params[:replace_all_es_actual]
      #logger.info("Setear a esta entidad como actual y reemplazar a las otras")
        dep = params[:entidad][:dependencia_id]
        crg = params[:entidad][:cargo_id]
        begin
            Entidad.transaction do
                Entidad.where(:dependencia_id => dep, :cargo_id => crg).update_all("es_actual = 0")
                @entidad.save!
            end
       rescue ActiveRecord::RecordInvalid => invalid
            ok=@entidad.save
            flash[:error] = "No se pudo actualizar el estado de las demas entidades"
       end

    else
      ok=@entidad.save
      if ok
          flash[:notice] =  'La Entidad se creo correctamente.'
      end
    end
    if ok
        respond_to do |format|
            format.html { redirect_to @entidad}
            format.json {
                # @entidad.joins(:dependencia).joins(:cargo).joins(:persona)
                #render :json => @entidad.to_json({:methods => :fullname, :only => [:id, :es_facultad ]}), status: :created, location: @entidad
                @hash_entidad = @entidad.as_json({:methods => [:fullname, :alias_or_fullname], :only => [:id, :es_facultad ]})
                if (params.key?(:hidden_params) && params[:hidden_params].size > 0)
                  @hashjson = @hash_entidad.merge(params[:hidden_params])
                else
                  @hashjson = @hash_entidad
                end
                render :json => @hashjson.to_json, status: :created, location: @entidad
            }
            # format.js             
        end
    else
        respond_to do |format|
            # format.html {
            #   render action: "new"
            # }
            format.json {
              render json: @entidad.errors, status: :unprocessable_entity
            }
            # format.js 
        end
    end
        # respond_to do |format|
        #     format.html {
        #       render action: "new"
        #     }
        #     format.json {
        #       render json: @entidad.errors, status: :unprocessable_entity
        #     }
        #     # format.js 
            
        # end
  end

  # PATCH/PUT /entidades/1
  def update
    if @entidad.update(entidad_params)
      respond_to do |format|
            format.html { redirect_to @entidad}
            format.json { render json: @hash_entidad = @entidad.to_json}
      end
    else
      respond_to do |format|
        format.html { redirect_to @entidad}
        format.json {render json: @entidad.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entidades/1
  def destroy
    @error_delete=false
    @msj_delete=""
    begin
      @entidad.destroy
      flash[:notice]= 'La entidad se elimino correctamente.'
      @msj_delete= 'La entidad se elimino correctamente.'
    rescue ActiveRecord::DeleteRestrictionError => e
      flash[:error]="No se pudo eliminar porque otros dependen de el\n(#{e})"
      @msj_delete = "No se pudo eliminar porque otros dependen de el\n(#{e})"
      @error_delete = true
    end
    redirect_to entidades_url
  end
  #lo mismo que destroy pero solo json
  def delete
    error_delete=false
    msj_delete=""
    begin
      @entidad.destroy
      msj_delete= 'La entidad se elimino correctamente.'
    rescue ActiveRecord::DeleteRestrictionError => e
      logger.info(e)
      msj_delete = "No se pudo eliminar porque otros dependen de el\n(#{e})"
      error_delete = true
    end
    respond_to do |format|
      format.json {
          result = {:error => error_delete,:msj => msj_delete}
          render json: result
      }
      format.js{$ok = !error_delete}
    end

  end
  # change es facultad /entidades/1
  def change_es_facultad
    params = ActionController::Parameters.new(es_facultad: !@entidad.es_facultad)
    respond_to do |format|
      if @entidad.update(params)
            format.json {
                result = {:error => false}
                render json: result
            }
            format.html{
              redirect_to entidades_url, notice: 'Se cambio el estado es miembro de la Facultad correctamente.'
            }
       else
            format.json {
                result = {:error => true}
                render json: result
            }
            format.html {redirect_to entidades_url, notice: 'Ocurrio un error al realizar el cambio.'}
       end
    end




  end
  # change es actual /entidades/1
  def change_es_actual
    params = ActionController::Parameters.new(es_actual: !@entidad.es_actual)
    respond_to do |format|
      if @entidad.update(params)
            format.json {
                result = {:error => false}
                render json: result
            }
            format.html{
              redirect_to entidades_url, notice: 'Se cambio el estado es Actual correctamente.'
            }
       else
            format.json {
                result = {:error => true}
                render json: result
            }
            format.html {redirect_to entidades_url, notice: 'Ocurrio un error al realizar el cambio.'}
       end
    end

  end
 def find_remitentes
    $s=params[:term]
    if(params[:dependencia_id])
        @entidades = Entidad.joins(:dependencia).where(:dependencia_id => params[:dependencia_id]).joins(:cargo).joins(:persona).search($s)
    else
        #@entidades = Entidad.joins(:dependencia).joins(:cargo).joins(:persona).search($s)
        @entidades = Entidad.search($s)
    end

app/helpers/entidades_helper.rb
module EntidadesHelper

    # PROCESA un string representando cargo y persona  e intenta obtenerlo de la base de datos.
    # el formato es "cargo: apellido, nombre"
    # Devuelve un hash con la siguiente informacion:
    # :cargo_text => texto con el cargo ingresado, nil si no se ingreso
    # :cargo => objeto Cargo si se encontro en la base de datos sino nil
    # :persona_text=> Apellido y nombre de la persona si no se ingreso nil
    # :persona => Objeto Persona  si se encontro en la base de datos sino nil

    def parse_text_to_cargo_persona(cp)
      pos = cp.index(':')
      textcargo = ""
      textpersona = ""
      if !pos.nil?
         # significa que esta el signo ':' o sea el cargo
          textcargo = cp[0,pos]
          textpersona = cp[pos+1..-1].strip
      else
        textpersona = cp
      end
      #separamos el apellido del nombre
      pos = textpersona.index(',')
      apellido = ""
      nombre = ""
      if !pos.nil?
         # significa que esta el signo '' o sea el apellido y nombre
          apellido = textpersona[0,pos]
          nombre = textpersona[pos+1..-1].strip
      else
        apellido = textpersona
      end

      textcargolike=textcargo.gsub(/[!%_]/) { |x| '!' + x }
      apellidolike=apellido.gsub(/[!%_]/) { |x| '!' + x }
      nombrelike=nombre.gsub(/[!%_]/) { |x| '!' + x }
      if !textcargo.blank?
        cargo = Cargo.where(nombre: textcargo).first || Cargo.where("nombre like ?","%#{textcargolike}%").first||nil
      end
      if !textpersona.blank?
        persona = Persona.where("apellido =? and nombre =?",apellido,nombre).first || Persona.where("apellido like ? and nombre like ?","%#{apellidolike}%","%#{nombrelike}%").first || nil
      end
      result = {:cargo_text =>textcargo, :cargo => cargo, :persona_text=> textpersona, :persona => persona }

    end


end

app/views/entidades/_js_form_remote.js.erb
<script>
/*Cuando se usa el autocomplete y se selecciona un objeto
  los metodos de abajo setean en la pagina el objeto seleccionado*/

<%
#fixed_persona_id indica que no se puede seleccionar persona, que ya viene fijo
if ! params.key?(:fixed_persona_id)
%>
/*Setea todos los campos necesarios para una persona seleccionada*/
function setPersona(fullname, id){
    $('#persona_fullname').val(fullname);
    $('#entidad_persona_id').val(id);
    $('#text_persona_id').html(id+ " - "+fullname);
}
<% end %>
<%
#fixed_dependencia_id indica que no se puede seleccionar dependencia, que ya viene fijo
if ! params.key?(:fixed_dependencia_id)
%>
/*Setea todos los campos necesarios para una dependencia seleccionada*/
function setDependencia(fullname, id){
    $('#dependencia_fullname').val("");
    $('#entidad_dependencia_id').val(id);
    $('#text_dependencia_id').html(id+ " - "+fullname);
}
<% end %>
<%
#fixed_cargo_id indica que no se puede seleccionar cargo, que ya viene fijo
if ! params.key?(:fixed_cargo_id)
%>
/* Setea todos los campos necesarios para un cargo seleccionado */
function setCargo(nombre, id){
    $('#cargo_fullname').val(nombre);
    $('#entidad_cargo_id').val(id);
    $('#text_cargo_id').html(id+ " - "+nombre);
}
<% end %>

/*Muestra o Esconde el checkbox que indica cambiar a es_actual a false para todas las otras entidades con
 el mismo cargo en la dependencia seleccionada*/
function showhide_replace_all_es_actual(){
    show = $("#entidad_es_actual").is(':checked');
    if (show)
        $("#divreplace_all_es_actual").show();
    else
        $("#divreplace_all_es_actual").hide();
}




$( document ).ready(function() {
    /*Inicializar campos cuando termina de cargar la pagina*/
    showhide_replace_all_es_actual();
    /*ASOCIAR LOS ENLACES A EVENTOS*/
    $('#link_crear_persona').click(function() {
        crearPersona("persona_fullname");
        return false;
    });
    $('#link_open_nueva_dependencia').click(function() {
        openNuevaDependencia();
        return false;
    });

    $('#link_crear_cargo').click(function() {
        crearCargo("cargo_fullname");
        return false;
    });

    <%
      #fixed_persona_id indica que no se puede seleccionar persona, que ya viene fijo y ya fue puesto en la pagina
      #si se puede seleccionar o buscar persona entonces es posible que este seleccionado uno asi que lo muestra
      if ! params.key?(:fixed_persona_id)
            if( @entidad.persona) #Si la entidad tiene asociada una persona
    %>
                setPersona('<%= raw(@entidad.persona.fullname) %>','<%= raw(@entidad.persona.id) %>');
   <%
            elsif params.key?(:persona_fullname)
   %>
            $('#persona_fullname').val('<%=raw(params["persona_fullname"])%>');
   <%      end   %>
        $('#persona_fullname').autocomplete({
            minLength: 0,
            source: '<%= personas_path(:json) %>',
            focus: function(event, ui) {
                //setPersona(ui.item.fullname,ui.item.id);
                $('#persona_fullname').val(ui.item.apellido+", "+ ui.item.nombre );
                return false;
            },
            select: function(event, ui) {
                setPersona(ui.item.apellido+", "+ ui.item.nombre,ui.item.id );
                return false;
            }
        }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li>" )
            .append( "<a>" +  item.apellido+", "+ item.nombre+"</a>" )
            .appendTo( ul );
        };



    <%  end %>
    <%
      #fixed_dependencia_id indica que no se puede seleccionar dependencia, que ya viene fijo y ya fue puesto en la pagina
      #si se puede seleccionar o buscar dependencia entonces es posible que este seleccionado uno asi que lo muestra
      if ! params.key?(:fixed_dependencia_id)
            if( @entidad.dependencia) #Si la entidad tiene asociada una dependencia
                concat (sanitize("setDependencia('"+raw(@entidad.dependencia.alias_or_fullname)+"',"+@entidad.dependencia.id.to_s+");"))
            elsif params.key?(:dependencia_fullname) && params.key?(:dependencia_id)
                concat (sanitize("setDependencia('"+raw(params["dependencia_fullname"])+"',"+params[:dependencia_id]+");"))
            end
    %>
        $('#dependencia_fullname').autocomplete({
            minLength: 0,
            source: '<%= dependencias_path(:json,params) %>',
            focus: function(event, ui) {
                $('#dependencia_fullname').val( ui.item.alias_or_fullname );
                return false;
            },
            select: function(event, ui) {
                //setDependencia("["+ui.item.codigo+"] "+ ui.item.nombre, ui.item.id);
                setDependencia(ui.item.alias_or_fullname, ui.item.id);
                return false;
            }
        }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li>" )
            .append( "<a>"+ item.alias_or_fullname+"</a>" )
            .appendTo( ul );
        };

    <%
      end
    %>
    <%
      #fixed_cargo_id indica que no se puede seleccionar cargo, que ya viene fijo y ya fue puesto en la pagina
      #si se puede seleccionar o buscar cargo entonces es posible que este seleccionado uno asi que lo muestra
      if ! params.key?(:fixed_cargo_id)
            if( @entidad.cargo) #Si la entidad tiene asociada un cargo
                concat (sanitize("setCargo('"+raw(@entidad.cargo.nombre)+"','"+raw(@entidad.cargo.id)+"');"))
            elsif params.key?(:cargo_fullname)

                concat (sanitize( "$('#cargo_fullname').val('"+raw(params["cargo_fullname"])+"');"))
            end
    %>
        $('#cargo_fullname').autocomplete({
            minLength: 2,
            source: '<%= cargos_path(:json) %>',
            focus: function(event, ui) {
                $('#cargo_fullname').val(ui.item.nombre );
                return false;
            },
            select: function(event, ui) {
                setCargo(ui.item.nombre, ui.item.id);
                return false;
            }
        }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
                return $( "<li>" )
            .append( "<a>" + item.nombre+"</a>" )
            .appendTo( ul );
        };



    <%
      end
    %>


});//fin ready


/*
 * Abre una ventana para crear nuevas dependencias
 * */
function openNuevaDependencia(){
    $('body').append("<div id='modal-dependencia'></div>");

    $.ajax({
       type: "GET"
       , url: "<%= url_for :controller =>"dependencias", :action=>'new', :remote=>'true' %>"
       , dataType:"html"
       , beforeSend: function(){
            //alert("Antes de enviar");
         }
       , complete: function(){
            //alert("Completo");
         }
       , success: function(data){
            $("#modal-dependencia").html(data);
         }
    });

    $("#modal-dependencia").dialog({
        autoOpen: false,
        height: 500,
        width: 600,
        modal: true,
        title: 'Nueva Dependencia',
        close: function(event, ui) { $('#modal-dependencia').remove();},

    });
    $("#modal-dependencia").dialog( "open" );
}
function postCreateDependencia(datajson){
    data = JSON.parse(datajson);
    //setDependencia("["+data['codigo']+"] "+data['nombre'],data['id']);
    setDependencia(data['alias_or_fullname'],data['id']);
    $("#modal-dependencia").dialog( "close" );
}
function postCreateEntidad(datajson){
    data = JSON.parse(datajson);
    $("#message-remote").html('<p class="alert">La Relacion se guardo correctamente'+data+'</p>');

    $("#modal-entidad").dialog( "close" );
}



















/*
 * Funcion para crear una nueva persona, los datos son tomados de un
 * campo de texto con la forma, apellido, nombres
 */
function crearPersona(fieldname){
    fullname= $("#"+fieldname).val();
    pos = fullname.indexOf(",");
    apellido = "";
    nombre = "";
    if(pos>0){
        apellido = fullname.substring(0,pos);
        nombre = fullname.substring(pos+1,fullname.length);
    }
    else
        apellido = fullname;
    apellido = trim(apellido);
    nombre = trim(nombre);
    var url = "<%= url_for :controller=>"personas", :action => "create" %>";
    $.ajax({
               type: "POST",
               dataType: "json",
               url: url,
               data: {"persona[nombre]":nombre, "persona[apellido]": apellido},
               success: function(data){
                  setPersona(data["apellido"]+", "+data["nombre"],data["id"]);
               },
               error: function(xhr, type, data){
                   alert("ERROR crear persona");
                   d=JSON.parse(xhr.responseText);
                   for (i in d) {
                     alert(d[i]);
                   };
               }

    });

        return false; // avoid to execute the actual submit of the form.
}


/*
 * Funcion para crear un nuevo cargo persona, los datos son tomados de un campo de texto
 */
function crearCargo(fieldname){
    nombre= $("#"+fieldname).val();

    var url = "<%= url_for :controller=>"cargos", :action => "create" %>";
    $.ajax({
               type: "POST",
               dataType: "json",
               url: url,
               data: {"cargo[nombre]":nombre},
               success: function(data){
                  setCargo(data["nombre"],data["id"]);
               },
               error: function(xhr, type, data){
                   d=JSON.parse(xhr.responseText);
                   for (i in d) {
                     alert(d[i]);
                   };
               }

    });

        return false; // avoid to execute the actual submit of the form.
}






</script>

app/views/entidades/_row_index.html.erb
<%
if !@entidades.empty?
    @entidades.each do |entidad|
        @entidad=entidad
        $cssclass=cycle('list-line-odd', 'list-line-even')
%>
<%= render partial: 'single_row_index' %>
  <% end %>
<div class="row">
<div class="tfoot">
<%= ajax_will_paginate @entidades, :id=>"div_pag_ajax", :previous_label=>"&lt;&lt;Ant", :next_label=>"Sig&gt;&gt;", :remote=>"true" %>
</div>
</div>
<%
  else
%>
<div class="row">
  <div  class="col-xs-12 col-sm-12 col-md-12  col-lg-12">
  <h2>No se encontraron resultados</h2>
  </div>
</div>

<% end %>

app/views/entidades/_script_index.js.erb
<script language="JavaScript">

function changeEsFacultad(id){

    url = "/entidades/"+id+"/change_es_facultad";
     $.ajax({
       type: "GET"
       , url: url
       , dataType:"json"
       , beforeSend: function(){/*alert("Antes de enviar");*/ }
       , complete: function(){/*alert("Completo");*/}
       , success: function(data){
            if(data["error"]){
                alert("No se pudo cambiar la condición");
            }
       }
    });
    //change_es_facultad
}
function changeEsActual(id){
    //change_es_actual

    url = "/entidades/"+id+"/change_es_actual";
     $.ajax({
       type: "GET"
       , url: url
       , dataType:"json"
       , beforeSend: function(){/*alert("Antes de enviar");*/ }
       , complete: function(){/*alert("Completo");*/}
       , success: function(data){
            if(data["error"]){
                alert("No se pudo cambiar la condición");
            }
       }
    });
}

</script>

app/views/entidades/edit.html.erb
<% if params[:remote] %>
    <div class="formulario">
      <div class="row">
        <div class="col-xs-12  col-sm-12  col-md-8  col-lg-8 col-md-offset-2  col-lg-offset-2">
          <%= render 'form_remote' %>
        </div>
      </div>
    </div>
<% else %>

<nav class="navbar" role="navigation">
  <%= navBarLink(@entidad,"Mostrar", "view16x16.png", {:title =>"Mostrar Entidad", :alt=>"Mostrar"})%>
  <%= navBarLink(entidades_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Entidades", :alt=>"Listar"})%>
</nav>

<div class="formulario">
    <div class="row">
      <div class="col-xs-6  col-sm-6  col-md-6  col-lg-6 col-md-offset-3 col-sm-offset-3 col-lg-offset-3">
        <h1>Editar Relación Cargo-Personas</h1>
        <%= render 'form_remote' %>
      </div>
    </div>
</div>
<% end %>

app/views/entidades/new.html.erb
<% if params[:remote] %>
    <div class="formulario">
      <div class="row">
        <div class="col-xs-12  col-sm-12  col-md-8  col-lg-8 col-md-offset-2  col-lg-offset-2">
          <%= render 'form_remote' %>
        </div>
      </div>
    </div>
<% else %>

  <nav class="navbar" role="navigation">
    <%= navBarLink(dependencias_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Dependencias", :alt=>"Listar"})%>
  </nav>
  <div class="formulario">
    <div class="row">
      <div class="col-xs-12  col-sm-12  col-md-8  col-lg-8 col-md-offset-2  col-lg-offset-2">
        <h1>Nueva Dependencia</h1>
        <%= render 'form' %>
     </div>
    </div>
   </div>

<% end %>

app/views/entidades/show.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(edit_entidad_path(@entidad),"Editar", "edit16x16.png", {:title =>"Editar Entidad", :alt=>"Editar"})%>
  <%= navBarLink(entidades_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Entidades", :alt=>"Listar"})%>
</nav>


<div class="box-key-values">
<h1>Detalle sobre la Relación entre el Cargo y la Persona</h1>
<p>
  <span class="text-key">Persona:</span>
  <%= @entidad.persona.fullname unless  @entidad.persona.nil? %>
</p>

<p>
  <span class="text-key">Dependencia:</span>
  <%= @entidad.dependencia.nombre unless  @entidad.dependencia.nil? %>
</p>

<p>
  <span class="text-key">Cargo:</span>
  <%= @entidad.cargo.nombre unless @entidad.cargo.nil? %>
</p>

<p>
  <span class="text-key">Es facultad:</span>
  <%= @entidad.es_facultad %>
</p>

<p>
  <span class="text-key">User:</span>
  <%= @entidad.user %>
</p>
</div>