config/routes.rb
Ssnotas::Application.routes.draw do

  resources :notas_attachment

  resources :estados_nota do
    get 'delete', on: :member
  end
  resources :nota_persona, only: :create
  resources :nota_persona do
     get 'delete', on: :collection
  end

  resources :home, only: :index
  root 'home#index'

  devise_for :users, path: "sessions", path_names: { sign_in: 'login', sign_out: 'logout', password: 'secret', confirmation: 'verification', unlock: 'unblock' }
  resources :users
  resources :users do
    member do
      get 'editpwd'
      post 'updatepwd'
    end
  end
  get "notas_recibidas/search"
  get "notas_recibidas"  => "notas_recibidas#index"
  get "notas_recibidas/:id" => "notas_recibidas#show" , as: "nota_recibida"
  post "versions/:id/revert" => "versions#revert", :as => "revert_version"

  resources :notas_temporales do
    get 'search', on: :collection
    get 'cupon', on: :member
    get 'barcode', on: :member

  end

  resources :notas_temporales

  resources :entidades do
    get 'change_es_facultad', on: :member
    get 'delete', on: :member
    get 'change_es_actual', on: :member
    get 'find_remitentes', on: :collection
    get 'find_destinatarios', on: :collection
    get 'get_actual_cargo_dependencia', on: :collection
    get 'search', on: :collection
  end
  resources :entidades

  resources :cargos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :personas do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "profile" => "profile#edit"
  post "profile/update" => "profile#update"
  get "profile/password" => "profile#password"
  post "profile/update_password" => "profile#update_password"

  resources :organismos do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  resources :notas do
    get 'search', on: :collection
    get 'search_pendientes', on: :collection
    get :new_dependencia,   :on => :collection
    post :create_dependencia,   :on => :collection
    get :new_remitente,   :on => :collection
    post :create_remitente,   :on => :collection
    get 'pendientes', on: :collection
    get 'edit_pendiente', on: :member
    post 'process_pendiente', on: :collection
    get 'barcode', on: :member
    post 'asociar', on: :collection
    get 'find_by', on: :collection
    get 'shortcut', on: :member
    get 'shortcut_pendiente', on: :member
    get 'att', on: :member    

  end

  resources :notas

  resources :destinatarios

  resources :autoridades

  resources :tipos_notas do
    get 'search', on: :collection
    get 'delete', on: :member
  end
  resources :remitentes do
    get :getByDependencia,   :on => :collection
  end

  resources :remitentes

  resources :dependencias do
    get 'search', on: :collection
    get 'delete', on: :member
  end

  get "datatable_i18n" => "datatable"
end

app/controllers/notas_controller.rb
class NotasController < ApplicationController
  include EntidadesHelper
  include ApplicationHelper
  helper_method :parse_text_to_cargo_persona
  #before_action :can_execute
  before_filter :authenticate_user!
  before_action :authenticate_manager, :clear_notice_side

  # GET /notas
  # GET /notas.json
  def index
      # @notas = Nota.paginate(:page => params[:page], :per_page => params[:rows])
      find_nota
      # respond_to do |format|
      #   format.html {render "/notas/bt/index" }
      #   format.json { render json: NotasDatatable.new(view_context) }
      # end
       @tipos_notas=TipoNota.all
       respond_to do |format|
         format.html
         format.json {render json: @notas }
         format.js
       end
  end

  #Realiza la busqueda de notas
  #El texto a buscar viene en el parametro term
  #Retorna una vista parcial de row_index
  def search
      find_nota
      respond_to do |format|
          format.html{render :partial=> "row_index"}
          format.js {  }
      end
  end

  #Realiza la busqueda de notas_pendientes
  #El texto a buscar viene en el parametro term
  #Retorna una vista parcial de row_index
  def search_pendientes
    session[:term] = params[:term]
      find_notas_pendientes
      #@notas_temporales.paginate(:page => params[:page], :per_page => params[:rows])

       respond_to do |format|
          format.html{render :partial=> "row_pendientes"}
          format.js {  }
      end
  end

  # GET /notas_temporales
  # Esto lo deberia ejecutar solo el administrador o mesa de entrada
  def pendientes
    #@notas_temporales = NotaTemporal.where(:estado => Nota::ESTADO_PENDIENTE).paginate(:page => params[:page], :per_page => params[:rows])
    find_notas_pendientes
    @notas_temporales.paginate(:page => params[:page], :per_page => params[:rows])
  end

# GET /notas/1/editpendiente
  def edit_pendiente
    @nota_temporal = NotaTemporal.find(params[:id])
    if !@nota_temporal.ingresada?
        @nota = @nota_temporal.to_nota
        #flash[:notice]="SOLO TENGO QUE ENTRAR ACA SI LA NOTA NO FUE PREVIAMENTE AGREGADA,HACER EL CHEQUEO EN EL CONTROLADOR DONDE ESTA ESTE TEXTO"
        if  @nota_temporal.remitente_id.nil?
          rem = parse_text_to_cargo_persona(@nota_temporal.texto_remitente)
          if !rem[:cargo].nil? && !rem[:persona].nil?
            r = Entidad.where(:cargo_id => rem[:cargo].id,  :persona_id => rem[:persona].id, :dependencia_id =>@nota_temporal.dependencia_id).first
            @nota_temporal.remitente_id = r.id unless r.nil?
          end
        end
        if  @nota_temporal.destinatario_id.nil?
          rem = parse_text_to_cargo_persona(@nota_temporal.texto_destinatario)
          if !rem[:cargo].nil? && !rem[:persona].nil?
            d = Entidad.where(:cargo_id => rem[:cargo].id,  :persona_id => rem[:persona].id, :dependencia_id =>Organismo::ID_FCEFQyN).first
            @nota_temporal.destinatario_id = d.id unless d.nil?
          end
        end
        @tipos_notas = TipoNota.all
    else
        flash[:error] = "El Documento ya ha sido procesado"
        redirect_to action: "pendientes"
    end

  end

  #POST Procesa la accion de edit_pendiente
  # da de alta la nota
  def process_pendiente
      @nota_temporal = NotaTemporal.find(params[:nota_temporal_id])
      @nota = Nota.new(nota_params_pendiente)
      @nota.fecha_ingreso = Time.now
      #si es de salida o entrada
      @nota.tipo = Nota::TIPO_ENTRADA
      #segun si es un administrativo o departamento
      @nota.estado = Nota::ESTADO_CIRCULACION
      @nota.cargado_mesa_entrada = false
      @u = current_user
      @nota.recibido_por_id = @u.id
      ok=true
      begin
          Nota.transaction do
              @nota.save!
              @nota_temporal.update_attributes!(:nota_id => @nota.id, :estado => Nota::ESTADO_CIRCULACION)
          end

      rescue ActiveRecord::RecordInvalid => invalid
          flash[:error] = invalid.message
          ok=false

      end

      respond_to do |format|
      if ok
        format.html { redirect_to @nota, notice: 'El Documento se creo correctamente.' }
        format.json { render json: @nota, status: :created, location: @nota }
      else
        format.html {
                     redirect_to :back
                    }
        format.json { render json: @nota.errors, status: :unprocessable_entity }
      end
    end
  end



  # GET /notas/1
  # GET /notas/1.json
  def show
    @nota = Nota.find(params[:id])
    current_uri = request.env['PATH_INFO']
    generate_barcode(@nota.codigo)
    @barcode = current_uri+'/barcode'
    # @nota_attachments = @nota.nota_attachments.all
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nota }
    end
  end
  def barcode
     @nota = Nota.find(params[:id])
     path = store_dir_barcode(@nota.codigo)
     #send_data path, :type => 'image/png', :filename => 'barcode.png'
     render :text => open(path, "rb").read
  end
  # GET /notas/new
  # GET /notas/new.json
  def new
      #Si es administrador o mesa de entrada
      if is_current_user_admin || is_current_user_sec_adm
            @nota = Nota.new
            @nota.fecha_ingreso = Time.now
            @dependencias = Dependencia.all
            # @estados_notas = EstadoNota.all
            #@remitentes = Remitente.all
            #@destinatarios = Destinatario.all
            @tipos_notas = TipoNota.all
            if params[:parent_id].present?
              @parent = Nota.find(params[:parent_id])
            end
            @nota_attachment = @nota.nota_attachments.build

            respond_to do |format|
              format.html {render "/notas/bt/new" }
              format.json { render json: @nota }
            end
        end
  end

  # GET /notas/1/edit
  def edit
      @nota = Nota.find(params[:id])
      @tipos_notas = TipoNota.all
      render "/notas/bt/edit" 
  end

  # POST /notas
  # POST /notas.json
  # Hay que tener en cuenta si es una nota de entrada o de salida, si fue cargada por un administrativo o desde un departamento
  def create
    nota_orig = Nota.new(nota_params)
    nota_orig.persona_ref_tokens = params["persona_ref_tokens"].split(",")
    params[:destinatarios]= params["destinatarios_token"].split(",")
    if !params[:destinatarios].nil? && params[:destinatarios].length > 0
          nota_orig.fecha_carga = Time.now
          #si es un administrativo
          nota_orig.fecha_ingreso = Time.now
          #si es de salida o entrada
          #nota_orig.tipo = Nota::TIPO_ENTRADA
          nota_orig.estado = Nota::ESTADO_CIRCULACION
          nota_orig.cargado_mesa_entrada = true
          @u = current_user
          nota_orig.cargado_por_id = @u.id
          nota_orig.recibido_por_id = @u.id
          #:parent_id,

          arr_notas = Array.new
          prepare_notas_ok=true
          params[:destinatarios].each do |value|
              @nota = nota_orig.dup
              @nota.destinatario_id =  value
              @nota.created_at = Time.now
              @nota.updated_at = Time.now
              if !@nota.valid?
                prepare_notas_ok = false
                break
              end
              arr_notas.push(@nota)
          end
          if prepare_notas_ok
                ok=true
                begin
                    Nota.transaction do
                      arr_notas.each do | nota |
                      @nota.save
                      end
                      # params[:destinatarios].each do |value|
                      #   @nota = nota_orig.dup
                      #   @nota.destinatario_id =  value
                      #   @nota.created_at = Time.now
                      #   @nota.updated_at = Time.now
                      #   # @nota.save!
                      #   if @nota.save
                      #     params[:nota_attachments]['filescan'].each do |a|
                      #     @nota_attachment = @nota.nota_attachments.create!(:filescan => a, :nota_id => @nota.id)
                      #     end
                      #   end
                      # end
                    end                
                rescue ActiveRecord::RecordInvalid => invalid
                    ok=false
                    flash[:error] = "No se pudo guardar el Documento"
                    puts  invalid.message
                    puts invalid.backtrace.inspect
                end
          end
    else
      flash[:error] = "Debe seleccionar al menos un destinatario"
      ok=false
    end
     respond_to do |format|
        if ok
            format.html { redirect_to @nota, notice: 'El Documento se creo correctamente.' }
            format.json { render json: @nota, status: :created, location: @nota }
        else
            unless defined? @nota
              #seteamos los atributos a nota
              @nota = Nota.new(nota_params)
            end
            format.html {
                       @dependencias = Dependencia.all
                       #@remitentes = Remitente.all
                       #@destinatarios = Destinatario.all
                       @tipos_notas = TipoNota.all
                       # render action: "new"
                       render "/notas/bt/new"
                      }
            format.json { render json: @nota.errors, status: :unprocessable_entity }
        end
     end
  end

  # PUT /notas/1
  # PUT /notas/1.json
  def update
    @nota = Nota.find(params[:id])
    @u = current_user
    if (params[:nota][:filescan].nil?)
      params[:nota][:recibido_por_id] = @u.id
      if is_current_user_admin || is_current_user_sec_adm
         params[:nota][:estado] = Nota::ESTADO_CIRCULACION
      end

      respond_to do |format|
        if @nota.update_attributes(nota_params_update)
          format.html { redirect_to @nota, notice: 'El Documento se modifico correctamente.' }
          format.json { head :no_content }
        else

          format.html {
            @tipos_notas = TipoNota.all

app/helpers/notas_helper.rb
module NotasHelper
  def hashTipo
    {Nota::TIPO_ENTRADA => "Entrada", Nota::TIPO_SALIDA => "Salida"}
  end
    def str_attr_tipo(tipo)
      if tipo == Nota::TIPO_ENTRADA
        return "ENTRADA"
      elsif tipo == Nota::TIPO_SALIDA
        return "SALIDA"
      else
        return "INDEFINIDO"
      end
    end

    def str_attr_estado(estado)
      if estado == Nota::ESTADO_PENDIENTE
        return "PENDIENTE"
      elsif estado == Nota::ESTADO_CIRCULACION
        return "CIRCULACION"
      else
        return "INDEFINIDO"
      end
    end

end

app/views/notas/_js_form_procesar_nota_pendiente.js.erb
<script>

function setDestinatario(nombre,id){
    $('#destinatario_fullname').val("");
    $('#nota_destinatario_id').val(id);
    $('#text_destinatario_id').html("["+id+"] - "+nombre);
}
function setRemitente(nombre,id){
    $('#remitente_fullname').val("");
    $('#nota_remitente_id').val(id);
    $('#text_remitente_id').html("["+id+"] - "+nombre);

}

/*
 * Abre una ventana para crear nuevos Remitentes
 * */
function openNuevoRemitente(esFacultad){
    //Crea un div donde pondra el formulario

    $('body').append("<div id='modal-remitente'></div>");
    //Llama remotamente a la accion new del controlador entidades diciendole que muestre todos las entidades
    if (esFacultad)
        url = "<%= url_for :controller =>"entidades", :action=>'new', :remote=>'true', :es_facultad=>'true',  :cargo_persona=>@nota_temporal.texto_remitente, :dependencia_id=>@nota_temporal.dependencia_id %>";
    else
        url = "<%= url_for :controller =>"entidades", :action=>'new', :remote=>'true', :es_facultad=>'false',  :cargo_persona=>@nota_temporal.texto_remitente, :dependencia_id=>@nota_temporal.dependencia_id %>"
    $.ajax({
       type: "GET"
       , url: url
       , dataType:"html"
       , beforeSend: function(){}
       , complete: function(){}
       , success: function(data){
            $("#modal-remitente").html(data);
       }
    });
    /*Especifica al div creado recientemente como dialog*/
    $("#modal-remitente").dialog({
        autoOpen: false,
        height: 570,
        width: 600,
        modal: true,
        title: 'Nuevo Remitente',
        close: function(event, ui) { $('#modal-remitente').remove();},

    });
    $("#modal-remitente").dialog( "open" );
}

/*
 * Abre una ventana para crear nuevos Destinatarios
 * */
function openNuevoDestinatario(esFacultad){
    $('body').append("<div id='modal-destinatario'></div>");
    if (esFacultad)
        url = "<%= url_for :controller =>"entidades", :action=>'new', :remote=>'true', :es_facultad=>'true', 'hidden_params[es_destinatario]'=>'true',  :cargo_persona=>@nota_temporal.texto_destinatario %>";
    else
        url = "<%= url_for :controller =>"entidades", :action=>'new', :remote=>'true', :es_facultad=>'false', 'hidden_params[es_destinatario]'=>'true' ,  :cargo_persona=>@nota_temporal.texto_destinatario %>";

    $.ajax({
       type: "GET"
       , url: url
       , dataType:"html"
       , beforeSend: function(){
            //alert("Antes de enviar");
         }
       , complete: function(){
            //alert("Completo");
         }
       , success: function(data){
            $("#modal-destinatario").html(data);
         }
    });

    $("#modal-destinatario").dialog({
        autoOpen: false,
        height: 580,
        width: 600,
        modal: true,
        title: 'Nuevo Destinatario',
        close: function(event, ui) { $('#modal-destinatario').remove();},

    });
    $("#modal-destinatario").dialog( "open" );
}


function postCreateEntidad(datajson, esDestinatario){
    /*Si era para remitente llamar a postCreateRemitente*/
    /*Si era para destinatario llamar a postCreateDestinatario*/
   if (esDestinatario)
        postCreateDestinatario(datajson);
   else
        postCreateRemitente(datajson);
}
function postCreateRemitente(datajson){

    data = JSON.parse(datajson);
    setRemitente(data['alias_or_fullname'],data['id']);
    $("#modal-remitente").dialog( "close" );
}
function postCreateDestinatario(datajson){
    data = JSON.parse(datajson);
    setDestinatario(data['alias_or_fullname'],data['id']);
    $("#modal-destinatario").dialog( "close" );
}



$( document ).ready(function() {
    <% if @nota_temporal && @nota_temporal.id
           if !@nota_temporal.destinatario.nil?
    %>
                setDestinatario("<%= raw @nota_temporal.destinatario.alias_or_fullname %>","<%= raw @nota_temporal.destinatario_id %>");

    <%
           else
    %>
           $('#destinatario_fullname').val("<%= raw @nota_temporal.texto_destinatario%>");
           //openNuevoDestinatario(false);
    <%       end
           if !@nota_temporal.remitente.nil?
    %>
                setRemitente("<%= raw @nota_temporal.remitente.alias_or_fullname %>","<%= raw @nota_temporal.remitente.id %>");
                //$("#div-sel-remitente").hide();

    <%
           else
           #El remitente ingresado no existe por ende hay que abrir la ventana para darlo de alta
           #pasando como parametro la dependencia para que se de  alta
    %>
          $('#remitente_fullname').val("<%= raw @nota_temporal.texto_remitente%>");
          //openNuevoRemitente(false);
    <%
           end
       elsif params[:nota]
           if params[:nota]['destinatario_id']
    %>
                setDestinatario("<%= raw params['destinatario_fullname']%>","<%= raw params[:nota]['destinatario_id'] %>");
    <%     end
           if params[:nota]['remitente_id']
    %>
                setRemitente("<%= raw params['remitente_fullname']%>","<%= raw params[:nota]['remitente_id']%>");
    <%
           end
       end
    %>

    $("#nota_fecha_ingreso" ).datepicker();
    /*----------------------------------------*/

    $('#remitente_fullname').autocomplete({
        minLength: 0,
        source: '<%=  find_remitentes_entidades_path(:json,{:dependencia_id=>@nota_temporal.dependencia_id}) %>',
        focus: function(event, ui) {
            $('#remitente_fullname').val(ui.item.alias_or_fullname);
                return false;
        },
        select: function(event, ui) {
                setRemitente(ui.item.alias_or_fullname, ui.item.id);
                return false;
        }/*,
        response: function( event, ui ) {
                alert(ui);
        }*/
    }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
        return $( "<li>" )
        .append( "<a> [" + item.id +"]" + item.alias_or_fullname+"</a>" )
        .appendTo( ul );
    };

    $('#destinatario_fullname').autocomplete({
        minLength: 0,
        source: '<%=  find_destinatarios_entidades_path(:json) %>',
        focus: function(event, ui) {
            $('#destinatario_fullname').val(ui.item.alias_or_fullname);
                return false;
        },
        select: function(event, ui) {
                setDestinatario(ui.item.alias_or_fullname, ui.item.id);
                return false;
        }/*,
        response: function( event, ui ) {
                alert(ui);
        }*/
    }).data( "ui-autocomplete" )._renderItem = function( ul, item ) {
        return $( "<li>" )
        .append( "<a> [" + item.id +"]" + item.alias_or_fullname+"</a>" )
        .appendTo( ul );
    };


  /* Indica que al hacer click en el enlace con id link_open_nuevo_remitente
   * llame a la funcion de js openNuevoRemitente
   * esto es para reemplazar el tag link_to_function que es deprecated en rails 4
  */
  $('#link_open_nuevo_remitente').click(function() {
    openNuevoRemitente(false);
    return false;
  });
 /* Indica que al hacer click en el enlace con id link_open_nuevo_remitente_facultad
   * llame a la funcion de js openNuevoRemitente
   * esto es para reemplazar el tag link_to_function que es deprecated en rails 4
  */
  $('#link_open_nuevo_remitente_facultad').click(function() {
    openNuevoRemitente(true);
    return false;
  });
  /* Indica que al hacer click en el enlace con id link_open_nuevo_destinatario
   * llame a la funcion de js openNuevoRemitente
   * esto es para reemplazar el tag link_to_function que es deprecated en rails 4
  */
  $('#link_open_nuevo_destinatario').click(function() {
    openNuevoDestinatario(false);
    return false;
  });
 /* Indica que al hacer click en el enlace con id link_open_nuevo_destinatario_facultad
   * llame a la funcion de js openNuevoRemitente
   * esto es para reemplazar el tag link_to_function que es deprecated en rails 4
  */
  $('#link_open_nuevo_destinatario_facultad').click(function() {
    openNuevoDestinatario(true);
    return false;
  });
});




</script>

app/views/notas/edit.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(@nota,"Mostrar", "view16x16.png", {:title =>"Mostrar Documento", :alt=>"Mostrar"})%>
  <%= navBarLink(notas_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Documentos", :alt=>"Listar"})%>
</nav>



<!-- <div class="form-v3"> -->
    <h1>Editar Documento</h1>
    <!-- <div class="panel">-->
      <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <%= render 'form_edit' %>
      </div>
    <!-- <aside class="menu_panel"> -->
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <%= render 'asociar' %>
        <br>
        <%= render 'dependiente'%>
        </div>
    <!-- </aside>-->
<!-- </div>-->

app/views/notas/edit_pendiente.html.erb
<%= render 'js_form_procesar_nota_pendiente.js' %>
<div class="form-v3">
    <div class="box-toolbar">
        <ul>
        <li><%= link_to image_tag("list16x16.png",{:align => "middle", :title =>"Ir al listado de Documentos pendientes", :alt=>"Listar", :border => "0"})+"Listado", pendientes_notas_path %></li>
        </ul>
    </div>

<h1>Dar ingreso a Documento Pendiente</h1>

<%= form_for @nota, url: process_pendiente_notas_path,  method: :post do |f| %>
<%= hidden_field_tag 'nota_temporal_id', @nota_temporal.id %>
<%= f.hidden_field :cargado_por_id %>
<%= f.hidden_field :codigo %>
<%= f.hidden_field :fecha_carga %>


  <% if @nota.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nota_temporal.errors.count, "error") %> produjo que el Documento no se guardara:</h2>
      <ul>
      <% @nota.errors.each_with_index do |msg, i| %>
          <li><%= msg[1] %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
      <h2>Codigo: <%= @nota.codigo %></h2>
  </div>
  <div class="field">
    <label for="remitente_fullname" class="required">Remitente</label>
    <p>
    <%= f.hidden_field :remitente_id %>
    <div id="div-sel-remitente">
    <input type="text" name="remitente_fullname" id="remitente_fullname" size="40" class="field"/>
    <%= link_to (image_tag("addModal.jpg",{:alt=>"Nuevo Remitente", :title=>"Abrir ventana Nuevo Remitente"})), "#", :id => "link_open_nuevo_remitente" %>
    <%= link_to (image_tag("add-02.png",{:alt=>"Nuevo Remitente Facultad", :title=>"Abrir ventana Nuevo Remitente de la Facultad"})), "#", :id => "link_open_nuevo_remitente_facultad" %>
    <br>
    </div>
    <strong>Remitente Seleccionado:</strong><br><span id="text_remitente_id" class="text-selected-obj"></span>
    </p>
  </div>




  <div class="field">
      <hr>
    <label for="destinatario_fullname" class="required">Destinatario

        </label>
        <p>
        <%= f.hidden_field :destinatario_id %>
        <input type="text" name="destinatario_fullname" id="destinatario_fullname" size="40" class="field"/>
        <%= link_to (image_tag("addModal.jpg",{:alt=>"Nuevo Destinatario", :title=>"Abrir ventana Nuevo Destinatario"})), "#", :id => "link_open_nuevo_destinatario" %>
        <%= link_to (image_tag("add-02.png",{:alt=>"Nuevo Destinatario Facultad", :title=>"Abrir ventana Nuevo Destinatario de la Facultad"})), "#", :id => "link_open_nuevo_destinatario_facultad" %><br>

        <strong>Destinatario seleccionado:</strong><br><span id="text_destinatario_id" class="text-selected-obj"></span>
        </p>
  </div>
    <div class="field">
        <hr>
        <%= f.label :tipo_nota_id, "Tipo de Nota", :class=>"required" %>
        <%= f.select :tipo_nota_id, @tipos_notas.collect {|p| [ p.nombre, p.id ] },{},{ :class=>"field small"} %>
        <span>&nbsp;&nbsp;</span>
        <%= f.label :fecha_nota , :class=>"required"%>
        <%= f.text_field :fecha_nota, :class=>"field small", :size =>"10", :value => (@nota.fecha_nota || Time.now).strftime('%d-%m-%Y') %>

    </div>
  <div class="field">
    <p><%= f.label :tema, "Descripción", :class=>"required" %><br />
    <%= f.text_field :tema, :class=>"field", :size=>"55" %></p>
  </div>
          <div class="field">
            <%= f.label :descripcion, "Observaciones" %><br />
            <%= f.text_area :descripcion, :class=>"field", :size=>"80x5" %>
          </div>
  <div class="actions">
    <center><%= f.submit "Aceptar", :class=>"button-v2" %></center>
  </div>
<% end %>

<div id="div-add-modal" title="Nueva Dependencia" style="display:none"></div>

</div>

app/views/notas/new.html.erb
<div class="form-v3">
    <div class="box-toolbar">
        <ul>
        <li><%= link_to image_tag("list16x16.png",{:align => "middle", :title =>"Ir al Listado", :alt=>"Listar", :border => "0"})+"Listado", notas_path %></li>
        </ul>
    </div>

    <h1>Nuevo Documento de Entrada</h1>
    <%= render 'form' %>
</div>

app/views/notas/show.html.erb
<nav class="navbar" role="navigation">
  <%= navBarLink(new_nota_path(:parent_id => @nota.id),"Asociar Nuevo Documento", "add16x16.png", {:title =>"Asociar Nuevo Documento", :alt=>"Asociar"})%>
  <%= navBarLink(edit_nota_path(@nota),"Editar", "edit16x16.png", {:title =>"Editar Documento", :alt=>"Editar"})%>
  <%= navBarLink(notas_path,"Listado", "list16x16.png", {:title =>"Ir al Listado de Documentos", :alt=>"Listar"})%>
</nav>

<div class="row">
    <!-- <div class="panel">-->
      <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <%= render 'show' %>
    </div>
    <!-- <aside class="menu_panel"> -->
      <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <%= render 'asociar' %>
        </div>
    <!-- </aside> -->

</div>